version: 2
jobs:
  build:
    working_directory: ~/cricket-frontend
    docker:
      - image: circleci/android:api-28-node
    steps:
      - checkout
      - run:
          command: sudo npm install -g nativescript
      - run:
          command: sudo tns usage-reporting disable
      - run:
          command: sudo tns error-reporting disable
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: 'tns build android --copy-to ~/cricket-frontend/build/android.apk'
      - store_artifacts:
          path: ~/cricket-frontend/build/
          prefix: android
